name: Azure Static Web Apps CI/CD

on:
  push:
    paths:
      - 'my-static-app/**'
      - '.github/workflows/azure-static-web-apps.yaml'
      - 'backend/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install Node.js and dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Ensure the Node.js version matches your app's requirement

      - name: Install Dependencies
        run: |
          cd my-static-app
          npm install

      # Build the React app
      - name: Build React App
        run: |
          cd my-static-app
          npm run build

      # Deploy to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SKY_04284081E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "my-static-app" # Set to my-static-app since that's where your app code is
          api_location: "" # Leave blank if no API
          output_location: "build" # Where the production build is located

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SKY_04284081E }}
          action: "close"
          app_location: "my-static-app" # Set to my-static-app here as well